[project]
name = "psychology-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "langchain>=0.3.14",
    "langchain-google-genai>=2.0.7",
    "python-dotenv>=1.0.1",
]
